-- ========================================
-- Longido Mountain Lodge Database Schema
-- ========================================
-- Run this in phpMyAdmin to set up the DB

CREATE DATABASE IF NOT EXISTS longido_lodge
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE longido_lodge;

-- ----------------------------------------
-- BOOKINGS TABLE
-- Stores all booking requests from website
-- ----------------------------------------
CREATE TABLE IF NOT EXISTS bookings (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  email VARCHAR(150) NOT NULL,
  phone VARCHAR(50),
  guests VARCHAR(10) NOT NULL,
  checkin DATE NOT NULL,
  checkout DATE NOT NULL,
  room VARCHAR(100) NOT NULL,
  message TEXT,
  status ENUM('new','contacted','confirmed','cancelled') DEFAULT 'new',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- ----------------------------------------
-- REVIEWS TABLE
-- Guest reviews — must be approved to show
-- ----------------------------------------
CREATE TABLE IF NOT EXISTS reviews (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  country VARCHAR(100),
  rating TINYINT NOT NULL CHECK (rating BETWEEN 1 AND 5),
  review_text TEXT NOT NULL,
  status ENUM('pending','approved','rejected') DEFAULT 'pending',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- ----------------------------------------
-- QUESTIONS / CONTACT MESSAGES
-- General questions or inquiries
-- ----------------------------------------
CREATE TABLE IF NOT EXISTS questions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  email VARCHAR(150) NOT NULL,
  subject VARCHAR(200),
  message TEXT NOT NULL,
  status ENUM('new','read','answered') DEFAULT 'new',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- ----------------------------------------
-- ADMIN USERS
-- For admin panel login
-- ----------------------------------------
CREATE TABLE IF NOT EXISTS admin_users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  full_name VARCHAR(100),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- ----------------------------------------
-- DEFAULT ADMIN USER
-- Username: admin   Password: admin123
-- (Hash for 'admin123' generated by PHP password_hash)
-- ----------------------------------------
INSERT INTO admin_users (username, password_hash, full_name) VALUES
('admin', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Lodge Manager')
ON DUPLICATE KEY UPDATE username = username;

-- ----------------------------------------
-- SAMPLE APPROVED REVIEWS
-- So website has reviews to show on first load
-- ----------------------------------------
INSERT INTO reviews (name, country, rating, review_text, status) VALUES
('Sarah & James', 'United Kingdom', 5,
 'An absolutely incredible experience! We hiked Longido Mountain with our teenage sons — a challenging but unforgettable all-day adventure. The lodge staff organised everything perfectly and the room was spotless.',
 'approved'),
('Marco Bianchi', 'Italy', 5,
 'Despite being simple, the lodge has a charm that modern hotels lack. The food was authentic and delicious — the Nyama Choma was the best I''ve had in Africa! The Maasai village walk was a highlight.',
 'approved'),
('Anna Kowalski', 'Poland', 4,
 'A tranquil gem off the beaten path. The gardens are beautiful and the rooms are clean and comfortable. The management was incredibly helpful when planning our activities. Very reasonable pricing!',
 'approved'),
('David Chen', 'Canada', 5,
 'We stumbled upon Longido Mountain Lodge while driving from Nairobi to Arusha and it was the best spontaneous decision of our trip! The staff welcomed us warmly and the food was fresh and delicious.',
 'approved');
